constants:
  swagger:
    info:
      title: Spring JPA
      description: 통합 작업
      version: v0.1
  jackson:
    date-format: yyyy-MM-dd
    datetime-format: yyyy-MM-dd HH:mm:ss

spring:
  application:
    name: SpringJPA
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/spring_jpa
    username: root
    password: green502
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        order_updates: true
    show-sql: true

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
